version: '2'
services:
  web:
    container_name: lyeung/jenkins-jdk8-maven3-base
    build: .
    image: jenkins:1.651.1 
    ports:
      - '50000:50000'
      - '9080:8080'
    volumes:
      - ~/docker-jenkins:/var/jenkins_home
